version: '3.8'
services:
 postgresql:
   image: postgres
   container_name: postgresql
   volumes:
     - postgresql-db:/var/lib/postgresql/data
   ports:
     - "5432:5432"
   env_file:
     - ./.env
   environment:
     - POSTGRES_DB=${DEV_DB_NAME}
     - POSTGRES_USER=${DEV_DB_USER}
     - POSTGRES_PASSWORD=${DEV_DB_PASSWORD}
   healthcheck:
     test: ["CMD-SHELL", "pg_isready -U ${DEV_DB_USER}"]
     interval: 10s
     timeout: 5s
     retries: 5

 django_gunicorn:
   build: ./
   volumes:
     - static:/app/project/static
     - media:/app/project/media
   env_file:
     - ./.env
   environment:
     - SECRET_KEY=${SECRET_KEY}
     - IS_DEV=${IS_DEV}
     - DEV_DB_HOST=${DEV_DB_HOST}
     - DEV_DB_PORT=${DEV_DB_PORT}
     - DEV_SUPERUSER_EMAIL=${DEV_SUPERUSER_EMAIL}
     - DEV_SUPERUSER_USERNAME=${DEV_SUPERUSER_USERNAME}
     - DEV_SUPERUSER_PASSWORD=${DEV_SUPERUSER_PASSWORD}
   ports:
     - "8000:8000"
   depends_on:
     postgresql:
       condition: service_healthy


 nginx:
   build: 
    context: ./nginx
    dockerfile: Dockerfile.dev
   volumes:
     - static:/static
     - media:/media
   ports:
     - "80:80"
   depends_on:
     - django_gunicorn

volumes:
 static:
 postgresql-db:
 media:
