version: '3.8'

services:
  postgresql:
    image: postgres
    container_name: postgresql
    volumes:
      - postgresql-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${PROD_DB_NAME}
      - POSTGRES_USER=${PROD_DB_USER}
      - POSTGRES_PASSWORD=${PROD_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PROD_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  django_gunicorn:
    image: ${DOCKERHUB_USERNAME}/portfolio-django_gunicorn:latest  # Pulling from Docker Hub
    volumes:
      - static:/app/project/static
      - media:/app/project/media
    env_file:
      - ./.env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - IS_DEV=${IS_DEV}
      - PROD_DB_HOST=${PROD_DB_HOST}
      - PROD_DB_PORT=${PROD_DB_PORT}
      - PROD_SUPERUSER_EMAIL=${PROD_SUPERUSER_EMAIL}
      - PROD_SUPERUSER_USERNAME=${PROD_SUPERUSER_USERNAME}
      - PROD_SUPERUSER_PASSWORD=${PROD_SUPERUSER_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      postgresql:
        condition: service_healthy

  nginx:
    image: ${DOCKERHUB_USERNAME}/portfolio-nginx:latest  # Pulling from Docker Hub
    env_file:
      - ./.env
    environment:
      - DOMAIN=${PROD_ALLOWED_HOST}
    volumes:
      - static:/static
      - media:/media
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt
      - nginx-ssl-conf:/vol/nginx_ssl_conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_gunicorn
  
  certbot:
    image: ${DOCKERHUB_USERNAME}/portfolio-certbot:latest
    environment:
      - EMAIL=${PROD_CERTBOT_EMAIL}
      - DOMAIN=${PROD_ALLOWED_HOST}
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt/
    depends_on:
      - nginx

volumes:
  static:
  postgresql-db:
  certbot-web:
  certbot-certs:
  nginx-ssl-conf:
  media: