# Generated by Django 5.0.3 on 2024-04-05 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationalInstiture',
            new_name='EducationalInstitute',
        ),
    ]
