# Generated by Django 5.0.3 on 2024-04-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_educationalinstiture_educationalinstitute'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
