# Generated by Django 5.0.3 on 2024-04-09 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile_location_alter_profile_first_name_and_more'),
        ('programming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('sub_title', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_skills', to='programming.category')),
                ('programming_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentation_skills', to='programming.programmingtool')),
            ],
        ),
    ]
