# Generated by Django 5.0.3 on 2024-04-05 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('sub_title', models.CharField(blank=True, default='', max_length=120)),
                ('image', models.FileField(upload_to='uploads/')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('sub_title', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programming_tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_tools', to='programming.programmingtool')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_tools', to='portfolioproject.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='programming_tools',
            field=models.ManyToManyField(through='portfolioproject.ProjectTools', to='programming.programmingtool'),
        ),
    ]
