# Generated by Django 5.0.3 on 2024-04-05 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioproject', '0001_initial'),
        ('programming', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectTools',
            new_name='ProjectTool',
        ),
    ]
