# Generated by Django 5.0.3 on 2024-04-21 06:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioproject', '0002_rename_projecttools_projecttool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
