name: "CI Pipeline"
# This CI workflow triggers on new PR or push on main branch.
# Todo: Using this wireframe, build the final pipeline

# This should be the original event outline
# on:
#   pull_request:
#     branches:
#       - main
#   push:
#     branches:
#       - main

# This is a test event outline for testing CI on test branch
on:
  push:
    branches:
      - github_actions

jobs:
  test_and_build:
    name: "Test and Build"
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v3
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2

      # Build docker images
      - name: Build and Run Docker Images
        run: docker-compose -f docker-compose.prod.yaml up --build

      # This handles all of our unit tests
      - name: "Run Unit Tests"
        run: docker-compose -f docker-compose.prod.yaml run django_gunicorn pytest

      # This checks syntax and styling standards
      - name: Run Linting
        run: docker-compose -f docker-compose.prod.yaml run django_gunicorn flake8 .

  # GitHub Security Scanning using CodeQL.This checks security vulnerabilities
  security_scan:
    name: "Security Scanning"
    runs-on: ubuntu-latest
    permissions:
      actions: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
